# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configuration_path.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PathConfiguration(object):
    def setupUi(self, PathConfiguration):
        PathConfiguration.setObjectName("PathConfiguration")
        PathConfiguration.resize(635, 585)
        self.centralwidget = QtWidgets.QWidget(PathConfiguration)
        self.centralwidget.setObjectName("centralwidget")
        self.configurePath_label = QtWidgets.QLabel(self.centralwidget)
        self.configurePath_label.setGeometry(QtCore.QRect(10, 10, 231, 16))
        self.configurePath_label.setObjectName("configurePath_label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 30, 621, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.apply_cancel_Button = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.apply_cancel_Button.setGeometry(QtCore.QRect(420, 490, 193, 28))
        self.apply_cancel_Button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.apply_cancel_Button.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel)
        self.apply_cancel_Button.setObjectName("apply_cancel_Button")
        self.audiveris_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.audiveris_lineEdit.setGeometry(QtCore.QRect(10, 70, 381, 31))
        self.audiveris_lineEdit.setObjectName("audiveris_lineEdit")
        self.audiveris_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.audiveris_pushButton.setGeometry(QtCore.QRect(400, 70, 93, 31))
        self.audiveris_pushButton.setObjectName("audiveris_pushButton")
        self.audiveris_label = QtWidgets.QLabel(self.centralwidget)
        self.audiveris_label.setGeometry(QtCore.QRect(10, 50, 101, 16))
        self.audiveris_label.setObjectName("audiveris_label")
        self.amazingmidi_label = QtWidgets.QLabel(self.centralwidget)
        self.amazingmidi_label.setGeometry(QtCore.QRect(10, 110, 121, 16))
        self.amazingmidi_label.setObjectName("amazingmidi_label")
        self.amazingmidi_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.amazingmidi_pushButton.setGeometry(QtCore.QRect(400, 130, 93, 31))
        self.amazingmidi_pushButton.setObjectName("amazingmidi_pushButton")
        self.amazingmidi_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.amazingmidi_lineEdit.setGeometry(QtCore.QRect(10, 130, 381, 31))
        self.amazingmidi_lineEdit.setObjectName("amazingmidi_lineEdit")
        self.reddotforever_label = QtWidgets.QLabel(self.centralwidget)
        self.reddotforever_label.setGeometry(QtCore.QRect(10, 170, 131, 16))
        self.reddotforever_label.setObjectName("reddotforever_label")
        self.reddotforever_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.reddotforever_pushButton.setGeometry(QtCore.QRect(400, 190, 93, 31))
        self.reddotforever_pushButton.setObjectName("reddotforever_pushButton")
        self.reddotforever_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.reddotforever_lineEdit.setGeometry(QtCore.QRect(10, 190, 381, 31))
        self.reddotforever_lineEdit.setObjectName("reddotforever_lineEdit")
        self.pianobooster_label = QtWidgets.QLabel(self.centralwidget)
        self.pianobooster_label.setGeometry(QtCore.QRect(10, 230, 121, 16))
        self.pianobooster_label.setObjectName("pianobooster_label")
        self.pianobooster_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pianobooster_pushButton.setGeometry(QtCore.QRect(400, 250, 93, 31))
        self.pianobooster_pushButton.setObjectName("pianobooster_pushButton")
        self.pianobooster_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.pianobooster_lineEdit.setGeometry(QtCore.QRect(10, 250, 381, 31))
        self.pianobooster_lineEdit.setObjectName("pianobooster_lineEdit")
        self.midisheetmusic_label = QtWidgets.QLabel(self.centralwidget)
        self.midisheetmusic_label.setGeometry(QtCore.QRect(10, 290, 141, 16))
        self.midisheetmusic_label.setObjectName("midisheetmusic_label")
        self.midiSheetMusic_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.midiSheetMusic_pushButton.setGeometry(QtCore.QRect(400, 310, 93, 31))
        self.midiSheetMusic_pushButton.setObjectName("midiSheetMusic_pushButton")
        self.midiSheetMusic_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.midiSheetMusic_lineEdit.setGeometry(QtCore.QRect(10, 310, 381, 31))
        self.midiSheetMusic_lineEdit.setObjectName("midiSheetMusic_lineEdit")
        self.xenoplay_label = QtWidgets.QLabel(self.centralwidget)
        self.xenoplay_label.setGeometry(QtCore.QRect(10, 350, 121, 16))
        self.xenoplay_label.setObjectName("xenoplay_label")
        self.xenoplay_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.xenoplay_pushButton.setGeometry(QtCore.QRect(400, 370, 93, 31))
        self.xenoplay_pushButton.setObjectName("xenoplay_pushButton")
        self.xenoplay_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.xenoplay_lineEdit.setGeometry(QtCore.QRect(10, 370, 381, 31))
        self.xenoplay_lineEdit.setObjectName("xenoplay_lineEdit")
        self.anthemscore_label = QtWidgets.QLabel(self.centralwidget)
        self.anthemscore_label.setGeometry(QtCore.QRect(10, 410, 191, 16))
        self.anthemscore_label.setObjectName("anthemscore_label")
        self.anthemscore_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.anthemscore_pushButton.setGeometry(QtCore.QRect(400, 430, 93, 31))
        self.anthemscore_pushButton.setObjectName("anthemscore_pushButton")
        self.anthemscore_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.anthemscore_lineEdit.setGeometry(QtCore.QRect(10, 430, 381, 31))
        self.anthemscore_lineEdit.setObjectName("anthemscore_lineEdit")
        PathConfiguration.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PathConfiguration)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 635, 26))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        PathConfiguration.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PathConfiguration)
        self.statusbar.setObjectName("statusbar")
        PathConfiguration.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(PathConfiguration)
        QtCore.QMetaObject.connectSlotsByName(PathConfiguration)

    def retranslateUi(self, PathConfiguration):
        _translate = QtCore.QCoreApplication.translate
        PathConfiguration.setWindowTitle(_translate("PathConfiguration", "Configure Program Path"))
        self.configurePath_label.setText(_translate("PathConfiguration", "Configure that path for each program."))
        self.audiveris_pushButton.setText(_translate("PathConfiguration", "Browse"))
        self.audiveris_label.setText(_translate("PathConfiguration", "Audiveris [folder]"))
        self.amazingmidi_label.setText(_translate("PathConfiguration", "AmazingMIDI [.exe]"))
        self.amazingmidi_pushButton.setText(_translate("PathConfiguration", "Browse"))
        self.reddotforever_label.setText(_translate("PathConfiguration", "Red Dot Forever [.exe]"))
        self.reddotforever_pushButton.setText(_translate("PathConfiguration", "Browse"))
        self.pianobooster_label.setText(_translate("PathConfiguration", "PianoBooster [.exe]"))
        self.pianobooster_pushButton.setText(_translate("PathConfiguration", "Browse"))
        self.midisheetmusic_label.setText(_translate("PathConfiguration", "Midi Sheet Music [.exe]"))
        self.midiSheetMusic_pushButton.setText(_translate("PathConfiguration", "Browse"))
        self.xenoplay_label.setText(_translate("PathConfiguration", "Xenoplay [.jar]"))
        self.xenoplay_pushButton.setText(_translate("PathConfiguration", "Browse"))
        self.anthemscore_label.setText(_translate("PathConfiguration", "AnthemScore [.exe] (Optional)"))
        self.anthemscore_pushButton.setText(_translate("PathConfiguration", "Browse"))
        self.menuHelp.setTitle(_translate("PathConfiguration", "Help"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PathConfiguration = QtWidgets.QMainWindow()
    ui = Ui_PathConfiguration()
    ui.setupUi(PathConfiguration)
    PathConfiguration.show()
    sys.exit(app.exec_())
